/** Stable ids for hand-drawn plant marker SVGs (not persisted yet). */
export const PLANT_ICON_IDS = [
  'seedling',
  'leaf-herb',
  'apple',
  'pear',
  'peach',
  'cherry',
  'strawberry',
  'blueberry',
  'lemon',
  'orange',
  'banana',
  'chestnut',
  'flower',
  'flower-blossom',
  'flower-tropical',
  'flower-spike',
  'flower-rose',
  'flower-rosette',
  'tree',
  'evergreen',
  'pea',
  'lettuce',
  'garlic',
  'onion',
  'grain',
  'potted',
  'grape',
  'kiwi',
  'sunflower',
  'maple',
  'plum',
  'apricot',
  'bouquet',
] as const;

export type PlantIconId = (typeof PLANT_ICON_IDS)[number];
