name: 'Test'
on: 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}-v${{ env.CACHE }}
    
    - name: 'Install Deps'
      run: npm ci
    
    - name: 'Test'
      id: test
      run: npm run test:coverage
    
    - name: 'Report Coverage'
      if: always() 
      uses:  davelosert/vitest-coverage-report-action@v2
    
    - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          retention-days: 2

    - name: Pass or fail
      if: ${{ steps.test.outcome == 'failure' }}
      uses: actions/github-script@v7
        with:
          script: core.setFailed('Tests failed!')

