name: 'CI'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

      - name: 'Install Deps'
        run: npm ci

      - name: 'Test'
        id: test
        run: npm run test:coverage

      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '27'

      - name: Test server
        env:
          DATABASE_URL: ecto://postgres:postgres@localhost:5432/permaplanner_test
        run: mix deps.get && mix test

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          retention-days: 2

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Pass or fail
        if: ${{ steps.test.outcome == 'failure' }}
        uses: actions/github-script@v7
        with:
          script: core.setFailed('Tests failed!')
