name: 'Update coverage on main branch'
on: 
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
    
    - name: 'Install Deps'
      run: npm ci
    
    - name: 'Test'
      id: test
      run: npm run test:coverage
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Pass or fail
      if: ${{ steps.test.outcome == 'failure' }}
      uses: actions/github-script@v7
      with:
        script: core.setFailed('Tests failed!')

